name: TelePad
main: com.kraken.telepad.TelePad
version: 1.5.2.6 (release)
commands: 
     telepad:
        description: Info on the TelePad plugin.
        usage: /<command>
     tele:
        description: Teleport to a set location.
        usage: /<command> <name>
     teleother:
        description: Teleport another (go to, or bring to).
        usage: /<command> <player> <go/bring>
     jump:
        description: Jump a short (~< 100m) distance.
        usage: /<command>
     teledel:
        description: Delete a teleport.
        usage: /<command> <name>
        aliases: [teledelete, tpdelete, tpdel]
     telelist:
        description: List teleports.
        usage: /<command>
        aliases: [tplist]
     teleset:
        description: Set a teleport.
        usage: /<command> <name>
        aliases: [tpset]
     opReqTP:
        description: Set the option to allow TP commands for OPs only.
        usage: /<command> <on/off>
        aliases: [opreqtp, oprequiredtp]
     permsReqTP:
        description: Set the option to allow TP commands for OPs only.
        usage: /<command> <on/off>
        aliases: [permsreqtp, permsrequiredtp]
     sparklesTP:
        description: Set the option to allow sparkle effects for teleports.
        usage: /<command> <on/off>
permissions:
     telepad.*:
        description: Permission for all TelePad commands.
        children:
           telepad.tp: true
           telepad.teleother: true
           telepad.telelist: true
           telepad.teleset: true
           telepad.teledel: true
           telepad.jump: true
           telepad.sparkles: true
     telepad.tp:
        description: Permission to use the 'tele' command.
     telepad.teleother:
        description: Permission to use the 'teleother' command.
     telepad.telelist:
        description: Permission to use the 'telelist' command.
     telepad.teleset:
        description: Permission to use the 'teleset' command.
     telepad.teledel:
        description: Permission to use the 'teledel' command.
     telepad.jump:
        description: Permission to use the 'jump' command.
     telepad.sparkles:
        description: Permission to have a sparkling effect on teleport.